scheduler:
  mode: continuous

  research_cycle:
    min_cycle_gap_seconds: 10
    max_cycle_gap_seconds: 60

  daily_limits:
    max_heavy_tasks: 5
    max_training_jobs: 1

  priority_weights:
    planning: 1.0
    research: 1.2
    experimentation: 1.5
    evaluation: 1.3
    reflection: 1.0
